[2023-10-01T15:47:10.632+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T15:47:10.645+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T15:47:10.645+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T15:47:11.764+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-01-02 06:00:00+00:00
[2023-10-01T15:47:11.779+0000] {standard_task_runner.py:57} INFO - Started process 626 to run task
[2023-10-01T15:47:11.783+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '567', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmp8jr6pnsp']
[2023-10-01T15:47:11.908+0000] {standard_task_runner.py:85} INFO - Job 567: Subtask load_gcs_to_bigquery
[2023-10-01T15:47:12.243+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T15:47:12.946+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-02T06:00:00+00:00'
[2023-10-01T15:47:12.948+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T15:47:12.949+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T15:47:12.950+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T15:47:12.998+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T15:47:12.998+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-01.csv.gz'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T15:47:12.999+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_01_02T06_00_00_00_00_3b1d428756790aeb5f1e96c4a0d9bb3e
[2023-10-01T15:47:15.551+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 436, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://practice18/green/green_tripdata_2019-01.csv.gz
[2023-10-01T15:47:15.861+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190102T060000, start_date=20231001T154710, end_date=20231001T154715
[2023-10-01T15:47:17.720+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 567 for task load_gcs_to_bigquery (404 Not found: URI gs://practice18/green/green_tripdata_2019-01.csv.gz; 626)
[2023-10-01T15:47:17.770+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-01T15:47:17.803+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T16:49:09.385+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T16:49:09.489+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T16:49:09.490+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T16:49:10.077+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-01-02 06:00:00+00:00
[2023-10-01T16:49:10.085+0000] {standard_task_runner.py:57} INFO - Started process 1584 to run task
[2023-10-01T16:49:10.089+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '578', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmpzvf8egme']
[2023-10-01T16:49:10.092+0000] {standard_task_runner.py:85} INFO - Job 578: Subtask load_gcs_to_bigquery
[2023-10-01T16:49:10.473+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T16:49:11.361+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-02T06:00:00+00:00'
[2023-10-01T16:49:11.363+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T16:49:11.363+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T16:49:11.364+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T16:49:11.424+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T16:49:11.425+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-01.csv.gz'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T16:49:11.426+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_01_02T06_00_00_00_00_a3af9e1256495762551500a84dfd4f61
[2023-10-01T16:49:17.643+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 436, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 922, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://practice18/green/green_tripdata_2019-01.csv.gz
[2023-10-01T16:49:18.257+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190102T060000, start_date=20231001T164909, end_date=20231001T164918
[2023-10-01T16:49:19.282+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 578 for task load_gcs_to_bigquery (404 Not found: URI gs://practice18/green/green_tripdata_2019-01.csv.gz; 1584)
[2023-10-01T16:49:19.375+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-01T16:49:19.411+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T17:27:57.652+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T17:27:58.194+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T17:27:58.194+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T17:27:58.957+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-01-02 06:00:00+00:00
[2023-10-01T17:27:59.004+0000] {standard_task_runner.py:57} INFO - Started process 2245 to run task
[2023-10-01T17:27:59.009+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '600', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmplimfdkk0']
[2023-10-01T17:27:59.012+0000] {standard_task_runner.py:85} INFO - Job 600: Subtask load_gcs_to_bigquery
[2023-10-01T17:28:00.063+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T17:28:00.538+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-02T06:00:00+00:00'
[2023-10-01T17:28:00.541+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T17:28:00.541+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T17:28:00.542+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T17:28:01.408+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T17:28:01.409+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-01.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T17:28:01.410+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_01_02T06_00_00_00_00_e249767463adc96c8b1149292a86edc1
[2023-10-01T17:28:01.764+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551f350>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:01.766+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551f6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:01.767+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551fa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:02.631+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854b7610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:02.635+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854b79d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:02.639+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854b7d90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:04.226+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854fea50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:04.229+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551f450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:04.232+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551fd10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:05.970+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854bd990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:05.972+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854bdd50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:05.973+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854c7150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:06.259+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854c7d10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:06.261+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854cf110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:06.263+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854cf4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:09.879+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854bda10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:09.882+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854bdd50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:09.886+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854bd6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:28.321+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551fa90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:28.324+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef8551fed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:28:28.328+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854feed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:29:02.904+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854dc150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:29:02.906+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854dc550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:29:02.908+0000] {connectionpool.py:824} WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fef854dc950>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /token
[2023-10-01T17:30:16.681+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190102T060000, start_date=20231001T172758, end_date=20231001T173016
[2023-10-01T17:30:17.593+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T17:30:17.644+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T18:42:38.520+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T18:42:38.563+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T18:42:38.563+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T18:42:38.604+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-01-02 06:00:00+00:00
[2023-10-01T18:42:38.615+0000] {standard_task_runner.py:57} INFO - Started process 3441 to run task
[2023-10-01T18:42:38.620+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '623', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmprsp9c83b']
[2023-10-01T18:42:38.623+0000] {standard_task_runner.py:85} INFO - Job 623: Subtask load_gcs_to_bigquery
[2023-10-01T18:42:38.679+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T18:42:38.840+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-02T06:00:00+00:00'
[2023-10-01T18:42:38.873+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T18:42:38.873+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T18:42:38.874+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T18:42:38.929+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T18:42:38.929+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-01.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T18:42:38.930+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_01_02T06_00_00_00_00_d375db0513d4ceb0f36ccef64d15c64b
[2023-10-01T18:42:58.867+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190102T060000, start_date=20231001T184238, end_date=20231001T184258
[2023-10-01T18:42:58.938+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T18:42:58.959+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-01T19:16:51.206+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T19:16:51.646+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [queued]>
[2023-10-01T19:16:51.646+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-10-01T19:16:51.717+0000] {taskinstance.py:1327} INFO - Executing <Task(GCSToBigQueryOperator): load_gcs_to_bigquery> on 2019-01-02 06:00:00+00:00
[2023-10-01T19:16:51.729+0000] {standard_task_runner.py:57} INFO - Started process 4028 to run task
[2023-10-01T19:16:51.734+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Load-Green-Taxi-Data-Web-To-GCS-To-BQ', 'load_gcs_to_bigquery', 'scheduled__2019-01-02T06:00:00+00:00', '--job-id', '627', '--raw', '--subdir', 'DAGS_FOLDER/web_gcs_bq.py', '--cfg-path', '/tmp/tmp6uc08nij']
[2023-10-01T19:16:51.737+0000] {standard_task_runner.py:85} INFO - Job 627: Subtask load_gcs_to_bigquery
[2023-10-01T19:16:51.916+0000] {task_command.py:410} INFO - Running <TaskInstance: Load-Green-Taxi-Data-Web-To-GCS-To-BQ.load_gcs_to_bigquery scheduled__2019-01-02T06:00:00+00:00 [running]> on host 772c7a5949f4
[2023-10-01T19:16:52.449+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Load-Green-Taxi-Data-Web-To-GCS-To-BQ' AIRFLOW_CTX_TASK_ID='load_gcs_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2019-01-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2019-01-02T06:00:00+00:00'
[2023-10-01T19:16:52.450+0000] {crypto.py:83} WARNING - empty cryptography key - values will not be stored encrypted.
[2023-10-01T19:16:52.451+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-10-01T19:16:52.452+0000] {gcs_to_bigquery.py:373} INFO - Using existing BigQuery table for storing data...
[2023-10-01T19:16:54.092+0000] {bigquery.py:2326} INFO - Project is not included in destination_project_dataset_table: alt_data.green_alt_data_table; using project "nature-26092023"
[2023-10-01T19:16:54.093+0000] {gcs_to_bigquery.py:377} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'nature-26092023', 'datasetId': 'alt_data', 'tableId': 'green_alt_data_table'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://practice18/green/green_tripdata_2019-01.csv'], 'writeDisposition': 'WRITE_APPEND', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'VendorID', 'type': 'INT64', 'mode': 'NULLABLE'}, {'name': 'lpep_pickup_datetime', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'lpep_dropoff_datetime', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'store_and_fwd_flag', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'RatecodeID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'PULocationID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'DOLocationID', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'passenger_count', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'trip_distance', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'fare_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'extra', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'mta_tax', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'tip_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'tolls_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'ehail_fee', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'improvement_surcharge', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'total_amount', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'payment_type', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'trip_type', 'type': 'FLOAT64', 'mode': 'NULLABLE'}, {'name': 'congestion_surcharge', 'type': 'FLOAT64', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': None, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2023-10-01T19:16:54.095+0000] {bigquery.py:1592} INFO - Inserting job ***_Load_Green_Taxi_Data_Web_To_GCS_To_BQ_load_gcs_to_bigquery_2019_01_02T06_00_00_00_00_25f2ea01f92033a20d04039382eb9705
[2023-10-01T19:17:10.101+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=Load-Green-Taxi-Data-Web-To-GCS-To-BQ, task_id=load_gcs_to_bigquery, execution_date=20190102T060000, start_date=20231001T191651, end_date=20231001T191710
[2023-10-01T19:17:10.252+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-01T19:17:10.270+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
